### ISSUE TITLE
SQL-Injection

### ISSUE THREAD

**Issue by b-3-n** [MrManchot/miniOrm#1]
I'm not an expert in this area but to me this library seems to be completely exposed to SQL-Injection attacks.

**Comment by MrManchot** [comment]
Yes, for the moment I just use it for personal little project, and no I don't check at all for security.
But you're right I'm going to check it really soon.

**Comment by b-3-n** [comment]
Okay. Thank you for answering. It is your project after all but I strongly recommend you to indicate these security issues clearly such that users know about them.

Best regards

Hans

**Comment by MrManchot** [comment]
Hello,

I check the code more precisely:
Every 'Insert' and 'Update' use PDO::quote => http://php.net/manual/en/pdo.quote.php
Seem to be Ok on this point.

For your exemple, as your use a 'Where condition' I think you have to protect your string yourself, doing something like that:

``` php
function delete_session_by_id ($id) {
    if(!$id) return false;
    miniOrm\Obj::find(array("session_id = '" . (int)$id . "'"), 'user_session');
}
```

I don't see major problem, but I'm not an expert security, If you see how I may improve it, I will be happy to :)

**Comment by b-3-n** [comment]
Using parameterized queries could be a good solution - although AFAIK this would require quite some modifications including changes in the API.
