### ISSUE TITLE
Decimal value is validated as string

### ISSUE THREAD

**Issue by jorr-it** [MrManchot/miniOrm#2]
Value for decimal field is validated as string, because a decimal field has a 'size' subkey in the vDescribe array too, causing an unjustied error that the value is too long. I guess this should be fixed in line 182-192 of Obj.php. I am willing to contribute to miniOrm and fix this this issue, please let me know how you would prefer this.

**Comment by MrManchot** [comment]
You can make a pull  request, I would be happy to validate it.
Have a nice day.

**Comment by jorr-it** [comment]
Done! Please let me know if it suits your requirements. Thank you.

**Comment by MrManchot** [comment]
Thank you, it's perfect. I Just merge and drop a release :)
